name: Health Check

on:
  push:
    branches:
      - main
      - feature/pr
  schedule:
    - cron: "15,55 * * * *"

jobs:
  HealthCheck:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-green-rain-7837.fly.dev/health'
          max-attempts: 3